# Generated by Django 4.0.4 on 2022-05-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
