# Generated by Django 4.0.4 on 2022-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
