# Generated by Django 4.0.4 on 2022-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_entriestime_date_alter_entriestime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entriestime',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='entriestime',
            name='user',
        ),
        migrations.AlterField(
            model_name='entriestime',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entriestime',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
