# Generated by Django 4.0.4 on 2022-05-09 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0009_remove_entriestime_barber_remove_entriestime_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'verbose_name': 'барбер', 'verbose_name_plural': 'барберы'},
        ),
        migrations.AddField(
            model_name='entriestime',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
