# Generated by Django 4.0.4 on 2022-05-09 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0010_alter_barber_options_entriestime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entriestime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
