# Generated by Django 4.0.4 on 2022-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_entriestime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entriestime',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entriestime',
            name='time',
            field=models.TimeField(),
        ),
    ]
