# Generated by Django 4.0.4 on 2022-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_services_delete_barber_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
