# Generated by Django 4.0.4 on 2022-05-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_comment_options_comment_barber_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='barber',
        ),
    ]
