# Generated by Django 4.0 on 2022-05-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
